### ISSUE TITLE
Evaluate the log-likelihood of ERGM

### ISSUE THREAD

**Issue by allenkei** [meleangelo/mfergm#1]
Dear Dr. Mele,

Thank you very much for the great package.

I am writing to inquire about what are some general methodology to evaluate the log-likelihood of ERGM, once we have the Mean Field approximation of the log normalizing constant (without directly calling R functions such as 'optimx()' in the package)?

Also, the ALGORITHM 1 in the paper for the Mean Field approximation assumes we have the parameter (\alpha, \beta, \gamma) and plug them in. Can we still learn the log normalizing constant if we do not have the parameter in advance?

Much appreciated and happy holidays! Sincerely,

**Comment by meleangelo** [comment]
I think these are two different questions. 
1) Can we evaluate the log-likelihood using the mean-field approximation?
Answer. YES, the log-likelihood function at a  particular parameter value (\alpha, \beta, \gamma) is given in the function loglikmf.model#.R. So for each parameter vector we can compute the value of the log-likelihood. 

2) Can we estimate the log-normalizing constant if we do not have the parameter in advance? 
Answer. YES, but this requires to find the approximate MLE, that is to maximize the log-likelihood with respect to \alpha, \beta, \gamma. To do that, we use optimx() in the package, but one could possibly evaluate the likelihood on a grid for the parameter vectors and find the vector that maximizes the log-likelihood function. Optimization on a grid is actually the most robust method, but it is clearly slow. One could parallelize the process of evaluating the log-likelihood and make it faster. 

I hope this helps.

**Comment by allenkei** [comment]
Dear Dr. Mele,

Thanks for your quick reply!

I was thinking if we can randomly initialize a parameter and use ALGORITHM 1 to estimate a normalizing constant. Next we update the parameter by maximize the log-likelihood given that normalizing constant, and then estimate a new normalizing constant again with the updated parameter. Basically solving the MLE and normalizing constant iteratively until they both converged. Does this sound like a valid process to estimate an ERGM given an observed network data in general?

If so, is there a more direct way to estimate the MLE given a known normalizing constant? (Since the original impossibility to estimate an exact MLE in ERGM is due to the intractable normalizing constant.)

Thank you so much again and I have learned a lot from you paper. Wish you a happy New Year!

**Comment by meleangelo** [comment]
This is what the optimization in the package is doing.
For an initial guess of the parameter vector, it computes the value of the constant and the log-likelihood. It keeps doing that until convergence. You can use different maximization routines (Nelder-Mead, for example, or BFGS, in optimx)

**Comment by allenkei** [comment]
Thank you so much for the answer!
